name: synchronized_tracked_time_list
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.1
  cloud_firestore: ^3.2.0
  crypto: ^3.0.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
